Added in automatic subnet selection- still need for start_stream

diff --git a/borealis_install b/borealis_install
--- a/borealis_install
+++ b/borealis_install
@@ -1,21 +1,34 @@
 #!bin/bash
 
-echo -e "Please enter the MAC address of your ground station laptop xx:xx:xx:xx:xx:xx\n"
-read MAC
+RED='\033[0;31m'
+GREEN='\033[0;32m'
+NC='\033[0m'
 
+#Prompts for and checks for proper MAC address
 while true; do
-        echo -e "Please enter the IP address of your ground station laptop\n in the form XXX.XXX.XXX.XXX\n"
-        read IP
-        if [[ $IP =~ ^([1-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])\.([0-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])\.([0-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])\.([1-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])$ ]]; then
-                echo "IP Correct"
-                exit 1;
-        else 
-                echo "IP Incorrect"
+
+        echo -e "Please enter the MAC address of your ground station laptop\nin the form XX:XX:XX:XX:XX:XX(Colon Separated)\n"
+        read MAC
+        if [[ $MAC =~ ^([0-9A-Fa-f]{2}:){5}[0-9A-Fa-f]{2}$ ]]; then
+                echo -e "${GREEN}Valid MAC address: $MAC${NC}"
+                break;
+        else
+                echo -e "\n${RED}Invalid MAC address (Incorrect Form or Values)${NC}"
         fi
+
 done
 
-#echo -e "Please which subnet you are operating on\n 1. 192.168.1.X\n 2. 192.168.2.X\n"
-#read IP
+#Prompts for and checks for proper IP address
+while true; do
+        echo -e "Please enter the IP address of your ground station laptop\nin the form XXX.XXX.XXX.XXX(Period Separated)\n"
+        read IP
+        if [[ $IP =~ ^([1-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])\.([0-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])\.([0-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])\.([1-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])$ ]]; then
+                echo -e "${GREEN}IP Correct: $IP${NC}"
+                exit 1;
+        else 
+                echo -e "\n${RED}IP Incorrect(Incorrect Form or Values)${NC}"
+        fi
+done
 
 sudo apt update
 
@@ -25,16 +38,6 @@ command5_output=$(git clone https://github.com/25nlambert/BOREALIS_Cam.git)
 echo "$command5_output"
 
 sudo dpkg -i BOREALIS_Cam/libcamera0_0~git20230707+2783c8d8-1_arm64.deb #Install modified libcamera
-
-#if [[ "$mac" = "" ]]
-#then
-#	mac="8c:0f:6f:6f:dc:e2"
-#fi
-
-#if [[ "$ip" = "" ]]
-#then
-#	ip="192.168.2.49"
-#fi
 
 sudo arp -S $IP $MAC #Set ARP mac address for ground laptop
 
@@ -53,10 +56,12 @@ sudo apt install -y tcpdump #So I can take a network dump
 
 sudo cp BOREALIS_Cam/config.txt /boot/config.txt #Replace config file with camera one
 
-third_octet=$(echo "$ip" | cut -d "." -f 3) #Modify dhcp file with correct
-
-
-sudo cp BOREALIS_Cam/dhcpcd.conf /etc/dhcpcd.conf #Replace dhcp file with working one for static IP
+#Finding and replacing to get on correct subnet
+third_octet=$(echo "$ip" | awk -F "." '{print $3}') #Find third_octet for subnet
+cp BOREALIS_Cam/dhcpcd.conf BOREALIS_Cam/dhcpcd.conf.modify #Create duplicate to modify
+sed "s/XX.XX.XX.XX/192.168.$third_octet.23/" <./BOREALIS_Cam/dhcpcd.conf.modify >./BOREALIS_Cam/dhcpcd.conf.modified #modify duplicate
+sudo cp BOREALIS_Cam/dhcpcd.conf.modified /etc/dhcpcd.conf 								#Replace dhcp file with working one for static IP
+rm ./BOREALIS_Cam/dhcpcd.conf.modify ./BOREALIS_Cam/dhcpcd.conf.modified				#remove duplicates
 
 sudo cp BOREALIS_Cam/.bashrc /home/pi/.bashrc #Replace shell config
 
